//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QLNH
{
    using System;
    using System.Collections.Generic;
    
    public partial class BillDetail
    {
        public string MaHD { get; set; }
        public string MaKH { get; set; }
        public string MaBan { get; set; }
        public string MaMon { get; set; }
        public string TenMon { get; set; }
        public int GiaTien { get; set; }
        public int SoLuongint { get; set; }
    
        public virtual Bill Bill { get; set; }
        public virtual Customer Customer { get; set; }
        public virtual Food Food { get; set; }
        public virtual Table Table { get; set; }
    }
}
