//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QLNH
{
    using System;
    using System.Collections.Generic;
    
    public partial class Bill
    {
        public string MaHD { get; set; }
        public int TongTien { get; set; }
    
        public virtual BillDetail BillDetail { get; set; }
    }
}
